[AdminUtils] Add channel create/rename/delete command
fixator10/Fixator10-Cogs pull request #126
Opened 2021-10-06 09:59 UTC by Predeactor

This PR resolve #19.

2021-10-06 12:02 UTC, fixator10 requested changes

2021-10-06 12:02 UTC, fixator10 commented on adminutils/adminutils.py
> +    @channel.command(name="create", aliases=["add"])
This allows user to create a channel in category, which user doesnt have access to.

For example, like category "archive" on screenshot:
![yes](https://moeka.is-a-good-waifu.com/AQnELRD.png)

2021-10-07 17:49 UTC, madebylydia commented on adminutils/adminutils.py
> +    @channel.command(name="create", aliases=["add"])
Should be fixed, I let you confirm me if it work now, and so I let you resolve this or not.

2021-10-09 10:24 UTC, fixator10 requested changes

2021-10-09 10:24 UTC, fixator10 commented on adminutils/adminutils.py
> +        channel_type: Optional[str] = "text",
`str` will never be optional. 
https://discordpy.readthedocs.io/en/stable/ext/commands/commands.html#typing-optional

Can be fixed via function thats returns True if arg is in list, or via custom Converter class

2021-10-09 10:24 UTC, fixator10 commented on adminutils/adminutils.py
> +                "The channel's type can only be `voice` or `text`."
i18n
```suggestion
                _("The channel's type can only be `voice` or `text`.")
```

2021-10-09 10:24 UTC, fixator10 commented on adminutils/adminutils.py
> +            else "You are not allowed to edit in this category."
i18n
```suggestion
            _("You are not allowed to edit this channel.")
            if not isinstance(channel_or_category, discord.CategoryChannel)
            else _("You are not allowed to edit in this category.")
```

2021-10-09 10:24 UTC, fixator10 commented on adminutils/adminutils.py
> +        category: Optional[discord.CategoryChannel] = None,
If category is not specified, it fails with `AttributeError: 'NoneType' object has no attribute 'permissions_for'`

2021-10-09 14:19 UTC, fixator10 approved these changes

2021-10-12 10:56 UTC, fixator10 approved these changes

2021-10-12 10:58 UTC, fixator10 commented
https://github.com/fixator10/Fixator10-Cogs/commit/fc0d7c7841f77396ef341b1b10b72bacd12a846b: *commited a info.json to a wrong branch*

2021-10-12 11:01 UTC, merged