Change `[p}thetime` it to a `timezone'd` time
fixator10/Fixator10-Cogs pull request #191
Opened 2022-09-26 21:31 UTC by Hedrauta

Still Servers time, but now "timezone'd"

Reason why:  server for my bot is in Germany, but most of my guilds members are living in US.... so, why not "timezone" it?

Changes
from  
https://i.imgur.com/nqjK5q7.png 
to
https://i.imgur.com/bitaahR.png

( which does looks different if you're in another timezone )

took me 10 minutes to learn the line and another 5 "testing" 😏  fails:
https://i.imgur.com/RnfxOpm.png
&
https://i.imgur.com/fEpr8SH.png
😆

2022-09-27 12:41 UTC, fixator10 requested changes

2022-09-27 12:41 UTC, fixator10 commented on moreutils/moreutils.py
> +import math
`math.floor` here is overkill, `int()` is more than enough

2022-09-27 12:41 UTC, fixator10 commented on moreutils/moreutils.py
> +        await ctx.send("<t:{}:f>".format(unix_timestamp))
There is an util for this in my utils "library", take a look for example in another cogs:

Example: https://github.com/fixator10/Fixator10-Cogs/blob/29e0655095e9b9a2aebd694e8bfc3ce59c502d59/steamcommunity/steamcommunity.py#L163
```py
def get_markdown_timestamp(
    timestamp: Union[datetime.datetime, int], style: TimestampStyle = None
) -> str:
```

2022-09-27 12:41 UTC, fixator10 commented on moreutils/moreutils.py
> +        """Displays the current time."""
This command was initially kinda created as SourceMod "easter egg":
https://wiki.alliedmods.net/Public_Commands_(SourceMod)

![img](https://moeka.is-a-good-waifu.com/9pGCZ9o.png)


Would be nice to have discord timestamp as nondefault argument, smth like
```py
async def _thetime(self, ctx, timestamp: bool = False):
    """Displays the current time of the server.
    If `<timestamp>` is True - show current time as discord timestamp"""
```

2022-09-28 23:12 UTC, Hedrauta commented
Allright... closing this PR.... i'll look and improve it, after I learned more about python....  
currently trying to write my own cog.
That implies, how to write python 😉 never did any python-code before 🤣 so own cog is my way to get into python 😆

2022-09-28 23:12 UTC, closed without merging