Add support to dpy2
fixator10/Fixator10-Cogs pull request #230
Opened 2023-10-23 15:34 UTC by ltzmax

This is a drafted pr where i'll add support for some expect those 2 prs thats already open to add support for it.

2023-10-23 15:56 UTC, ltzmax commented
Alright, should be ready now. 
The only i didnt do: steamcommunity, reverseimagesearch and captcha
- Steamcommunity require to support current lib version which it doesn't, either lock to a version where it works or add support for current.
- reverseimagesearch couldnt get api to test it.
- captcha require some work.

2023-10-24 09:31 UTC, fixator10 requested changes

2023-10-24 09:31 UTC, fixator10 commented on datautils/__init__.py
> +    await create_task(setup_after_ready(bot))
[create_task](https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task) is sync function
```suggestion
    create_task(setup_after_ready(bot))
```

2023-10-24 09:31 UTC, fixator10 commented on generalchannel/__init__.py
> +    await bot.add_cog(cog)
Why adding an variable here?
```suggestion
async def setup(bot):
    await bot.add_cog(GeneralChannel(bot))
```

2023-10-24 09:31 UTC, fixator10 commented on godvilledata/__init__.py
> +    await bot.add_cog(cog)
Same here
```suggestion
    await bot.add_cog(GodvilleData(bot))
```

2023-10-24 09:31 UTC, fixator10 commented on massthings/__init__.py
> +    await bot.add_cog(cog)
```suggestion
async def setup(bot):
    await bot.add_cog(MassThings(bot))
```

2023-10-24 09:31 UTC, fixator10 commented on moreutils/__init__.py
> +    await create_task(setup_after_ready(bot))
[create_task](https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task) is sync function
```suggestion
    create_task(setup_after_ready(bot))
```

2023-10-24 10:33 UTC, ltzmax commented
also note for `weather`, the api is apple's now and will no longer allow you to make api + the current api you have seems to be deleted by apple so i was not able to test the cog properly.

2023-10-24 10:34 UTC, fixator10 commented
Ye, thats known, i most likely will need to rewrite it entirely

2023-12-31 22:54 UTC, fixator10 approved these changes
Datautils failing, but its not init issue, taking it from here

2023-12-31 22:55 UTC, merged