[feature]emoji steal
fixator10/Fixator10-Cogs pull request #46
Opened 2020-09-02 05:14 UTC by kablekompany

Steal emoji from a message using message.id
(probably not the best logic in mirroring your own but sharing nonetheless!

2020-09-03 09:46 UTC, fixator10 requested changes

2020-09-03 09:46 UTC, fixator10 commented on adminutils/adminutils.py
> +    @emoji.command(name="steal")
```suggestion
    @emoji.command(name="message", aliases=["steal"])
```

2020-09-03 09:46 UTC, fixator10 commented on adminutils/adminutils.py
> +    async def emote_steal(self, ctx, name: str, message_id: int, *roles: discord.Role):
```suggestion
    async def emote_steal(self, ctx, name: str, message_id: discord.Message, *roles: discord.Role):
```

2020-09-03 09:46 UTC, fixator10 commented on adminutils/adminutils.py
> +        """
```suggestion
        """
        Add emoji from a message ID and add it to your server.
        Use double quotes if role name has spaces

        Examples:
            `[p]emoji steal Example 162379234070467641`
            `[p]emoji steal RoleBased 162379234070467641 EmojiRole`
        """
```

2020-09-03 09:46 UTC, fixator10 commented on adminutils/adminutils.py
> +        message = await channel.fetch_message(message_id)
```suggestion
```

Not needed with message converter

2020-09-03 09:46 UTC, fixator10 commented on adminutils/adminutils.py
> +                data = await r.read()
```suggestion
        async with self.session.get(url) as r:
            data = await r.read()
```

Cog already have a session for that.

This also will throw an `check your logs` error if emoji is unable to unload, this better to be handled too. Look at how `emoji_add` handles that

2020-09-03 09:46 UTC, fixator10 commented on adminutils/adminutils.py
> +            format_image = "png"
This better to be redone with regex.

In example, as it done in [TrustyCogs' notsobot converter](https://github.com/TrustyJAID/Trusty-cogs/blob/a3e931bc6227645007b37c3f4f524c9fc9859686/notsobot/converter.py#L30-L36).

2020-09-03 09:46 UTC, fixator10 commented on adminutils/adminutils.py
> +                    ("Restricted to roles: {}").format(
```suggestion
                    _("Restricted to roles: {}").format(
```
i18n support

2020-09-03 09:46 UTC, fixator10 commented on adminutils/adminutils.py
> +            return
```suggestion
        except discord.HTTPException as e:
            await ctx.send(chat.error(_("An error occurred on adding an emoji: {}").format(e)))
```
HTTPException can happen not only on hitting emoji limit.
About emoji limit - perhaps even better handle this at start of command via check for count of current server emojis and total available emojis (`guild.emoji_limit`)

2020-09-03 09:46 UTC, fixator10 commented on adminutils/adminutils.py
> +                "Make sure there's an emoji in that messageID and you're running this command correctly (`[p]emoji steal nameTheEmote <msgID>`) Extra numbers in the message will throw this error too.
```suggestion
                _("This image type is not supported anymore or Discord returned incorrect data. Try again later.")
```

2020-09-03 09:46 UTC, fixator10 commented on adminutils/adminutils.py
> +            e.set_thumbnail(url=ctx.guild.icon_url)
Other commands doesn't have any message on success.
```suggestion
```

2020-09-05 04:15 UTC, kablekompany commented
Cant' appease black for some reason but requested changes were committed/performed

2020-09-05 04:19 UTC, fixator10 approved these changes

2020-09-05 04:19 UTC, merged

2020-09-05 04:21 UTC, fixator10 commented
Thanks for contribution

2020-09-05 04:22 UTC, kablekompany commented
thanks for your guidance and patience. Cheers!