Fix wrong import check
fixator10/Fixator10-Cogs pull request #80
Opened 2021-02-19 14:24 UTC by Predeactor

Don't PR right now, I'll check before and tell you if it's good

2021-02-19 18:16 UTC, Predeactor commented
should be good

2021-02-20 17:03 UTC, fixator10 requested changes

2021-02-20 17:03 UTC, fixator10 commented on leveler/commands/lvlset/profile.py
> +            if not all(module in modules for module in ("numpy", "scipy")):
```suggestion
            if not all(module in modules for module in ("numpy", "scipy.cluster")):
```
`cluster` may, *or may not* depend on some others packages, and, iirc, not load even if scipy itself is loaded.

2021-02-20 17:29 UTC, fixator10 approved these changes

2021-02-20 18:05 UTC, merged